modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dimmense"
version="1.0.0"
displayName="Dimmense"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jack, MCreator"

[[dependencies.dimmense]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



